[package]
name = "assemblers-solver"
version = "0.2.0"
authors = ["Igaguri <igagurimk@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.7"